# Site settings
title: Moonlight
description: > # this means to ignore newlines until "baseurl:"
  No-framework admin theme.
baseurl: "/moonlight" # the subpath of your site, e.g. /blog/
url: "http://moonshotproject.github.io" # the base hostname & protocol for your site
github_username:  MoonshotProject

# Build settings
markdown: kramdown
